### ISSUE TITLE
List Retail Ready SKUs To eBay

### ISSUE THREAD

**Issue by AlexJupiter** [AlexJupiter/volo2#1]
**Definition of Done**
A user can upload an excel sheet with multiples one SKUs in each of the eight categories:
- Jeans
- Skirts
- Jupmsuits & playsuits
- Shorts
- Top & Shirts
- Dresses
- Coats & jackets
- Trousers

A user will be able to test this by logging into their eBay account.

**Sub Tasks**
- [ ] Remove ebay_uk prefix from payloads sent to Cresco
- [ ] Refactor listing_handler_service to be generic of channel objects received (sellers, products, offers)
- [ ] REvolve listing error, event and status objects to be type agnostic (eg, works for seller, product, offer)
- [ ] complete UAT for eBay integration
